#!/usr/bin/python3
from sys import argv
import math
"""will factorize as many numbers into a product of 2 smaller numbers"""


def fact(numb):
    """This function gets the factors of a number"""
    if numb % 2 == 0:
        m = 2
        print("{}={}*{}".format(numb, int(numb//m), m))
    else:
        sqr = int(math.sqrt(numb)) + 1
        for m in range(3, sqr, +2):
            if numb % m == 0:
                print("{}={}*{}".format(numb, int(numb//m), m))
                return
            if numb % (sqr + m) == 0:
                print("{}={}*{}".format(numb, sqr + m, int(numb//(sqr + m))))
                return
            if numb % (sqr - m) == 0:
                print("{}={}*{}".format(numb, sqr - 1, int(numb//(sqr - m))))
                return


def theFactors(fle_name):
    """function will read file and print them"""

    with open(fle_name, encoding="utf-8") as myFile:
        for x in myFile.readlines():
            n = int(x)
            answer = fact(n)


if __name__ == "__main__":
    theFactors(argv[1])
